import React, { useState, useEffect } from 'react';
import { Landmark, ArrowUpRight, CheckCircle, AlertCircle, XOctagon, CheckSquare, Coins } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { motion, AnimatePresence } from 'framer-motion';
import { API_BASE_URL } from '../../config';

const PayoutSettler = () => {
  const { token } = useAuth();
  const [withdrawals, setWithdrawals] = useState([]);
  const [loading, setLoading] = useState(true);
  const [notification, setNotification] = useState(null);
  const [actionInProgress, setActionInProgress] = useState(null);

  const fetchPendingWithdrawals = async (showLoader = true) => {
    try {
      if (showLoader) setLoading(true);
      const res = await fetch(`${API_BASE_URL}/api/admin/withdrawals/pending`, {
        headers: {
          'x-auth-token': token
        }
      });
      if (res.ok) {
        const data = await res.json();
        setWithdrawals(data.withdrawals || []);
      } else {
        showNotification({ type: 'error', text: 'Failed to fetch withdrawal requests.' });
      }
    } catch (err) {
      console.error(err);
      showNotification({ type: 'error', text: 'Network connection failed.' });
    } finally {
      if (showLoader) setLoading(false);
    }
  };

  useEffect(() => {
    if (token) {
      fetchPendingWithdrawals(true);
      const interval = setInterval(() => fetchPendingWithdrawals(false), 10000);
      return () => clearInterval(interval);
    }
  }, [token]);

  const showNotification = (msg) => {
    setNotification(msg);
    setTimeout(() => setNotification(null), 3000);
  };

  const handleSettlement = async (id, status) => {
    try {
      setActionInProgress(id);
      const res = await fetch(`${API_BASE_URL}/api/admin/withdrawals/${id}/settle`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          'x-auth-token': token
        },
        body: JSON.stringify({ status })
      });

      if (res.ok) {
        showNotification({
          type: 'success',
          text: `Withdrawal successfully ${status === 'settled' ? 'marked as settled' : 'declined'}.`
        });
        // Remove item from UI state
        setWithdrawals(prev => prev.filter(w => w._id !== id));
      } else {
        showNotification({ type: 'error', text: 'Failed to complete payout action.' });
      }
    } catch (err) {
      console.error(err);
      showNotification({ type: 'error', text: 'Network request error.' });
    } finally {
      setActionInProgress(null);
    }
  };

  return (
    <div className="space-y-8 pb-12">
      {/* Header Section */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-aakaa-green tracking-tight">Withdrawal Payouts</h1>
          <p className="text-aakaa-gold text-sm font-medium mt-1">
            Review and settle earnings withdrawal requests generated by caregivers.
          </p>
        </div>
      </div>

      {/* Notifications */}
      <AnimatePresence>
        {notification && (
          <motion.div
            initial={{ opacity: 0, y: -20, x: 20 }}
            animate={{ opacity: 1, y: 0, x: 0 }}
            exit={{ opacity: 0, scale: 0.95 }}
            className={`fixed top-24 right-8 text-white px-8 py-4 rounded-[1.5rem] shadow-2xl z-50 flex items-center gap-3 font-bold text-sm border border-white/10 ${
              notification.type === 'error' ? 'bg-red-500' : 'bg-aakaa-green'
            }`}
          >
            {notification.type === 'error' ? <AlertCircle size={18} /> : <CheckCircle size={18} />}
            {notification.text}
          </motion.div>
        )}
      </AnimatePresence>

      {/* Requests Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        <AnimatePresence mode="popLayout">
          {loading ? (
            <div className="col-span-full py-24 text-center">
              <div className="animate-spin w-10 h-10 border-4 border-aakaa-green border-t-transparent rounded-full mx-auto mb-4"></div>
              <p className="text-aakaa-gold font-black">Syncing transaction ledger...</p>
            </div>
          ) : withdrawals.length > 0 ? (
            withdrawals.map((req, index) => (
              <motion.div
                layout
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.95 }}
                transition={{ delay: index * 0.05 }}
                key={req._id}
                className="bg-white rounded-[2.5rem] border border-aakaa-green/5 premium-shadow overflow-hidden group hover:scale-[1.02] transition-all duration-500 flex flex-col justify-between"
              >
                <div className="p-8">
                  {/* Therapist info */}
                  <div className="flex items-center gap-4 mb-6">
                    <img
                      src={req.therapistId?.avatarUrl || 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop'}
                      alt={req.therapistId?.fullName || 'Therapist'}
                      className="w-12 h-12 rounded-xl object-cover border border-aakaa-green/5 shadow-sm"
                    />
                    <div>
                      <h3 className="font-black text-aakaa-green text-base leading-tight">
                        {req.therapistId?.fullName || 'Therapist'}
                      </h3>
                      <p className="text-[10px] text-aakaa-gold font-black uppercase tracking-wider">
                        Requested on {new Date(req.createdAt).toLocaleDateString()}
                      </p>
                    </div>
                  </div>

                  {/* Payout Details */}
                  <div className="bg-aakaa-cream/20 rounded-2xl p-5 border border-aakaa-green/5 space-y-4">
                    <div className="flex items-baseline justify-between border-b border-aakaa-green/5 pb-3">
                      <span className="text-[10px] text-aakaa-gold font-black uppercase tracking-widest">Amount</span>
                      <span className="text-2xl font-black text-aakaa-green">₹{req.amount.toLocaleString()}</span>
                    </div>

                    <div className="space-y-3 pt-1">
                      <div className="flex items-center gap-2 text-xs font-black text-aakaa-green uppercase tracking-wider">
                        <Landmark size={14} className="text-aakaa-gold" />
                        <span>{req.payoutMode === 'upi' ? 'UPI Route' : 'Bank Direct'}</span>
                      </div>

                      {req.payoutMode === 'upi' ? (
                        <div className="bg-white rounded-lg p-2.5 border border-aakaa-green/5 text-xs font-mono font-bold text-aakaa-green select-all">
                          {req.therapistDetails?.upiId || req.destinationDetails?.upiId || 'N/A'}
                        </div>
                      ) : (
                        <div className="space-y-2 text-xs font-bold text-aakaa-gold">
                          <div className="flex justify-between">
                            <span className="opacity-60">Holder:</span>
                            <span className="text-aakaa-green">{req.therapistDetails?.accountHolderName || req.destinationDetails?.accountHolderName || 'N/A'}</span>
                          </div>
                          <div className="flex justify-between">
                            <span className="opacity-60">Bank:</span>
                            <span className="text-aakaa-green">{req.therapistDetails?.bankName || req.destinationDetails?.bankName || 'N/A'}</span>
                          </div>
                          <div className="flex justify-between">
                            <span className="opacity-60">IFSC:</span>
                            <span className="text-aakaa-green font-mono">{req.therapistDetails?.ifscCode || req.destinationDetails?.ifscCode || 'N/A'}</span>
                          </div>
                          <div className="flex justify-between border-t border-aakaa-green/5 pt-2">
                            <span className="opacity-60">Account Number:</span>
                            <span className="text-aakaa-green font-mono select-all bg-white px-2 py-0.5 rounded border border-aakaa-green/5">{req.therapistDetails?.accountNumber || req.destinationDetails?.accountNumber || 'N/A'}</span>
                          </div>
                        </div>
                      )}
                    </div>
                  </div>
                </div>

                {/* Verification Actions */}
                <div className="p-8 border-t border-aakaa-green/5 flex gap-2">
                  <button
                    disabled={actionInProgress !== null}
                    onClick={() => handleSettlement(req._id, 'rejected')}
                    className="flex-1 flex items-center justify-center gap-2 py-3.5 bg-red-50 text-red-600 hover:bg-red-100/70 rounded-xl text-xs font-black uppercase tracking-wider transition-all disabled:opacity-50"
                  >
                    <XOctagon size={14} />
                    <span>Decline</span>
                  </button>
                  <button
                    disabled={actionInProgress !== null}
                    onClick={() => handleSettlement(req._id, 'settled')}
                    className="flex-1 flex items-center justify-center gap-2 py-3.5 bg-aakaa-green text-white hover:bg-aakaa-green/90 rounded-xl text-xs font-black uppercase tracking-wider transition-all shadow-md shadow-aakaa-green/10 disabled:opacity-50"
                  >
                    <CheckSquare size={14} />
                    <span>Settle Payout</span>
                  </button>
                </div>
              </motion.div>
            ))
          ) : (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="col-span-full py-24 text-center">
              <div className="flex flex-col items-center gap-4">
                <Coins size={64} className="text-aakaa-gold/20" />
                <p className="text-aakaa-gold font-black text-xl">Payout queue is empty.</p>
                <p className="text-aakaa-gold/60 text-sm">All withdrawal requests have been successfully settled.</p>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
};

export default PayoutSettler;
